
services:
    pi-llm:
        build: 
            context: src/.
            dockerfile: Dockerfile.win
        env_file: 
            - ./env_docker/docker_user_dir.env
        container_name: "pi-llm"
        group_add:
            - audio 
            # - sound
            - pulse
            - pulse-access
            # - wslg
        volumes:
            - $ENV_VOLUME:$ENV_VOLUME
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /run/user/$ENV_UID/pulse:/run/user/$ENV_UID/pulse
            - $ENV_VOLUME/.config/pulse:$ENV_VOLUME/.config/pulse 
            - /var/run/pulse/:/var/run/pulse/
            - /mnt/wslg/PulseServer:/mnt/wslg/PulseServer
            #- $ENV_VOLUME/.config/pulse/cookie:/root/.config/pulse/cookie
            #- ~/.config/pulse/cookie:~/.config/pulse/cookie

            #- $ENV_PWD/files/pulseaudio.client.conf:/etc/pulse/client.conf.d/client.conf
            #- $ENV_USER_DIR/.config/pulse:$ENV_USER_DIR/.config/pulse
        environment:
            - PULSE_SERVER=unix:/run/user/$ENV_UID/pulse/native
            #- PULSE_SERVER=unix:/mnt/wslg/PulseServer 
            #- PULSE_SERVER=tcp:127.0.0.1
            - XDG_RUNTIME_DIR=/var/run/user/$ENV_UID
            #- DISPLAY=${DISPLAY:-:0}
            - DISPLAY=127.0.0.1:0.0
            - PULSE_COOKIE=~/.config/pulse/cookie
        user: ${ENV_UID}:${ENV_GID} 
        devices:
            - /dev/snd:/dev/snd
        privileged: true
#volumes:
#    $ENV_VOLUME:

