
services:
    pi-llm:
        build: 
            context: src/.
            dockerfile: Dockerfile.win
            args:
              - ENV_IP=$ENV_IP
              - ENV_PULSE_SERVER=$ENV_PULSE_SERVER
        port:
            - 4713:4713 
        env_file: 
            - ./env_docker/docker_user_dir.env
            - ./env_docker/docker_pulse_server.env 
        container_name: "pi-llm"
        group_add:
            - audio 
            # - sound
            - pulse
            - pulse-access
            # - wslg
        volumes:
            - $ENV_VOLUME:$ENV_VOLUME
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /var/run/user/$ENV_UID/:/var/run/user/$ENV_UID/
            - $ENV_VOLUME/.config/pulse:$ENV_VOLUME/.config/pulse 
            - /mnt/wslg/PulseServer:/mnt/wslg/PulseServer
        environment:
            - PULSE_SERVER=unix:/mnt/wslg/PulseServer
            #/var/run/user/$ENV_UID/pulse/native
            - ENV_IP=$ENV_IP
            - XDG_RUNTIME_DIR=/var/run/user/$ENV_UID
            - DISPLAY=127.0.0.1:0.0
            - PULSE_COOKIE=$ENV_VOLUME/.config/pulse/cookie
        user: ${ENV_UID}:${ENV_GID} 
        devices:
            - /dev/snd:/dev/snd
        privileged: true
#volumes:
#    $ENV_VOLUME:

