
services:
    pi-llm:
        build: 
            context: .
            dockerfile: Dockerfile.win
            args:
              - ENV_IP
              - ENV_PULSE_SERVER=$ENV_PULSE_SERVER
              - ENV_USER_DIR
              - XDG_RUNTIME_DIR=/var/run/user/$ENV_UID/
              - ENV_VOLUME=$ENV_VOLUME
              - ENV_UID
        env_file: 
            - ./pulseaudio-win.env
        container_name: "pi-llm"
        group_add:
            - audio 
            - pulse
            - pulse-access
        volumes:
            #- /tmp/.X11-unix:/tmp/.X11-unix
            - /var/run/user/${ENV_UID}/:/var/run/user/${ENV_UID}/
            - /mnt/wslg/PulseServer:/mnt/wslg/PulseServer
            - ${ENV_VOLUME}/:${ENV_VOLUME}/
        environment:
            - PULSE_SERVER=unix:/mnt/wslg/PulseServer
            - ENV_IP=$ENV_IP
            - XDG_RUNTIME_DIR=/var/run/user/$ENV_UID
            - DISPLAY=127.0.0.1:0.0
            - PULSE_COOKIE=$ENV_VOLUME/.config/pulse/cookie
        devices:
            - /dev/snd:/dev/snd
        privileged: true

